package com.airos.pos.app

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import java.util.Locale

internal enum class CashierLanguage {
    FI,
    EN,
}

internal enum class CashierStringKey {
    RailActive,
    RailTables,
    RailMenu,
    RailTransactions,
    RailScan,
    RailShift,
    RailSettings,
    RailSignOut,
    TransactionsTitle,
    TransactionsSupporting,
    TransactionsCurrent,
    TransactionsPast,
    TransactionsSearchPlaceholder,
    TransactionsRangeAll,
    TransactionsRangeToday,
    TransactionsRangeLast7Days,
    TransactionsRangeLast30Days,
    TransactionsFilterAll,
    TransactionsStatusOpen,
    TransactionsStatusPaid,
    TransactionsStatusSynced,
    TransactionsStatusPending,
    TransactionsStatusFailed,
    TransactionsStatusBlocked,
    TransactionsPaymentAll,
    TransactionsPaymentCash,
    TransactionsPaymentCard,
    TransactionsPaymentVoucher,
    TransactionsPaymentMixed,
    TransactionsListEmptyCurrent,
    TransactionsListEmptyPast,
    TransactionsDetailEmpty,
    TransactionsCurrentSummary,
    TransactionsReceiptPreview,
    TransactionsTimeline,
    TransactionsTimelineEmpty,
    TransactionsActionReprint,
    TransactionsActionRefund,
    TransactionsActionCorrect,
    TransactionsNoLineItems,
    TransactionsSubtotal,
    TransactionsDiscount,
    TransactionsTax,
    TransactionsTotal,
    TransactionsFieldTime,
    TransactionsFieldReceipt,
    TransactionsFieldSaleId,
    TransactionsFieldTable,
    TransactionsFieldCashier,
    TransactionsFieldCorrectionActor,
    TransactionsFieldAmount,
    TransactionsFieldPaymentMethod,
    TransactionsFieldStatus,
    TransactionsFieldSync,
    TransactionsFieldPublicReceipt,
    TransactionsFieldUpdated,
    TransactionsUnavailable,
    TransactionsWalkIn,
    TransactionsTimelineOpened,
    TransactionsTimelineTransferred,
    TransactionsTimelineFinalized,
    TransactionsTimelineSynced,
    TransactionsTimelineFailed,
    TransactionsTimelineBlocked,
    TransactionsPublicReceiptReady,
    TransactionsPublicReceiptPending,
}

internal class CashierStrings(private val language: CashierLanguage) {
    operator fun get(key: CashierStringKey): String {
        return cashierTranslations[language]?.get(key)
            ?: cashierTranslations[CashierLanguage.EN]?.get(key)
            ?: key.name
    }
}

@Composable
internal fun rememberCashierStrings(): CashierStrings {
    val language = remember {
        when (Locale.getDefault().language.trim().lowercase(Locale.ROOT)) {
            "fi" -> CashierLanguage.FI
            else -> CashierLanguage.EN
        }
    }
    return remember(language) { CashierStrings(language) }
}

private val cashierTranslations: Map<CashierLanguage, Map<CashierStringKey, String>> = mapOf(
    CashierLanguage.FI to mapOf(
        CashierStringKey.RailActive to "Aktiivinen",
        CashierStringKey.RailTables to "Poydat",
        CashierStringKey.RailMenu to "Menu",
        CashierStringKey.RailTransactions to "Tapahtumat",
        CashierStringKey.RailScan to "Scan",
        CashierStringKey.RailShift to "Shift",
        CashierStringKey.RailSettings to "Asetukset",
        CashierStringKey.RailSignOut to "Kirjaudu ulos",
        CashierStringKey.TransactionsTitle to "Tapahtumat",
        CashierStringKey.TransactionsSupporting to "Nykyiset tulevat open sale -totuudesta. Menneet tulevat durable local sales ledger outboxista.",
        CashierStringKey.TransactionsCurrent to "Nykyiset",
        CashierStringKey.TransactionsPast to "Menneet",
        CashierStringKey.TransactionsSearchPlaceholder to "Hae kuittia, poytaa, kassahenkiloa tai tapahtumaa",
        CashierStringKey.TransactionsRangeAll to "Kaikki",
        CashierStringKey.TransactionsRangeToday to "Tanaan",
        CashierStringKey.TransactionsRangeLast7Days to "7 pv",
        CashierStringKey.TransactionsRangeLast30Days to "30 pv",
        CashierStringKey.TransactionsFilterAll to "Kaikki",
        CashierStringKey.TransactionsStatusOpen to "Avoin",
        CashierStringKey.TransactionsStatusPaid to "Maksettu",
        CashierStringKey.TransactionsStatusSynced to "Synced",
        CashierStringKey.TransactionsStatusPending to "Odottaa syncia",
        CashierStringKey.TransactionsStatusFailed to "Sync epaonnistui",
        CashierStringKey.TransactionsStatusBlocked to "Estetty",
        CashierStringKey.TransactionsPaymentAll to "Kaikki tavat",
        CashierStringKey.TransactionsPaymentCash to "Kateinen",
        CashierStringKey.TransactionsPaymentCard to "Kortti",
        CashierStringKey.TransactionsPaymentVoucher to "Voucher",
        CashierStringKey.TransactionsPaymentMixed to "Yhdistetty",
        CashierStringKey.TransactionsListEmptyCurrent to "Ei avoimia tapahtumia nykyisilla filttereilla.",
        CashierStringKey.TransactionsListEmptyPast to "Ei menneita tapahtumia nykyisilla filttereilla.",
        CashierStringKey.TransactionsDetailEmpty to "Valitse tapahtuma oikean paneelin detailia varten.",
        CashierStringKey.TransactionsCurrentSummary to "Avoimen laskun yhteenveto",
        CashierStringKey.TransactionsReceiptPreview to "Kuittinakyma",
        CashierStringKey.TransactionsTimeline to "Tapahtumaketju",
        CashierStringKey.TransactionsTimelineEmpty to "Ei authoritatiivista tapahtumaketjua tasta lahteesta.",
        CashierStringKey.TransactionsActionReprint to "Tulosta uudelleen",
        CashierStringKey.TransactionsActionRefund to "Hyvita",
        CashierStringKey.TransactionsActionCorrect to "Korjaa tapahtumaa",
        CashierStringKey.TransactionsNoLineItems to "Ei riveja.",
        CashierStringKey.TransactionsSubtotal to "Valisumma",
        CashierStringKey.TransactionsDiscount to "Alennus",
        CashierStringKey.TransactionsTax to "Vero",
        CashierStringKey.TransactionsTotal to "Yhteensa",
        CashierStringKey.TransactionsFieldTime to "Aika",
        CashierStringKey.TransactionsFieldReceipt to "Kuitti",
        CashierStringKey.TransactionsFieldSaleId to "Sale",
        CashierStringKey.TransactionsFieldTable to "Poyta",
        CashierStringKey.TransactionsFieldCashier to "Myynnin teki",
        CashierStringKey.TransactionsFieldCorrectionActor to "Korjasi",
        CashierStringKey.TransactionsFieldAmount to "Summa",
        CashierStringKey.TransactionsFieldPaymentMethod to "Maksutapa",
        CashierStringKey.TransactionsFieldStatus to "Status",
        CashierStringKey.TransactionsFieldSync to "Sync",
        CashierStringKey.TransactionsFieldPublicReceipt to "Julkinen kuitti",
        CashierStringKey.TransactionsFieldUpdated to "Paivitetty",
        CashierStringKey.TransactionsUnavailable to "Ei authoritatiivista tietoa",
        CashierStringKey.TransactionsWalkIn to "Walk-in",
        CashierStringKey.TransactionsTimelineOpened to "Lasku avattu",
        CashierStringKey.TransactionsTimelineTransferred to "Lasku siirretty",
        CashierStringKey.TransactionsTimelineFinalized to "Maksu viimeistelty paikallisesti",
        CashierStringKey.TransactionsTimelineSynced to "Myynti synkattu backendiin",
        CashierStringKey.TransactionsTimelineFailed to "Backend-sync epaonnistui",
        CashierStringKey.TransactionsTimelineBlocked to "Backend hylkasi myynnin",
        CashierStringKey.TransactionsPublicReceiptReady to "Valmis",
        CashierStringKey.TransactionsPublicReceiptPending to "Ei viela saatavilla",
    ),
    CashierLanguage.EN to mapOf(
        CashierStringKey.RailActive to "Active",
        CashierStringKey.RailTables to "Tables",
        CashierStringKey.RailMenu to "Menu",
        CashierStringKey.RailTransactions to "Transactions",
        CashierStringKey.RailScan to "Scan",
        CashierStringKey.RailShift to "Shift",
        CashierStringKey.RailSettings to "Settings",
        CashierStringKey.RailSignOut to "Sign out",
        CashierStringKey.TransactionsTitle to "Transactions",
        CashierStringKey.TransactionsSupporting to "Current items come from open sale truth. Past items come from the durable local sales ledger outbox.",
        CashierStringKey.TransactionsCurrent to "Current",
        CashierStringKey.TransactionsPast to "Past",
        CashierStringKey.TransactionsSearchPlaceholder to "Search receipt, table, cashier, or event",
        CashierStringKey.TransactionsRangeAll to "All",
        CashierStringKey.TransactionsRangeToday to "Today",
        CashierStringKey.TransactionsRangeLast7Days to "7 days",
        CashierStringKey.TransactionsRangeLast30Days to "30 days",
        CashierStringKey.TransactionsFilterAll to "All",
        CashierStringKey.TransactionsStatusOpen to "Open",
        CashierStringKey.TransactionsStatusPaid to "Paid",
        CashierStringKey.TransactionsStatusSynced to "Synced",
        CashierStringKey.TransactionsStatusPending to "Pending sync",
        CashierStringKey.TransactionsStatusFailed to "Sync failed",
        CashierStringKey.TransactionsStatusBlocked to "Blocked",
        CashierStringKey.TransactionsPaymentAll to "All methods",
        CashierStringKey.TransactionsPaymentCash to "Cash",
        CashierStringKey.TransactionsPaymentCard to "Card",
        CashierStringKey.TransactionsPaymentVoucher to "Voucher",
        CashierStringKey.TransactionsPaymentMixed to "Mixed",
        CashierStringKey.TransactionsListEmptyCurrent to "No open transactions match the current filters.",
        CashierStringKey.TransactionsListEmptyPast to "No past transactions match the current filters.",
        CashierStringKey.TransactionsDetailEmpty to "Select an event to open the detail pane.",
        CashierStringKey.TransactionsCurrentSummary to "Open bill summary",
        CashierStringKey.TransactionsReceiptPreview to "Receipt preview",
        CashierStringKey.TransactionsTimeline to "Timeline",
        CashierStringKey.TransactionsTimelineEmpty to "No authoritative timeline is available from this source.",
        CashierStringKey.TransactionsActionReprint to "Print again",
        CashierStringKey.TransactionsActionRefund to "Refund",
        CashierStringKey.TransactionsActionCorrect to "Correct transaction",
        CashierStringKey.TransactionsNoLineItems to "No line items.",
        CashierStringKey.TransactionsSubtotal to "Subtotal",
        CashierStringKey.TransactionsDiscount to "Discount",
        CashierStringKey.TransactionsTax to "Tax",
        CashierStringKey.TransactionsTotal to "Total",
        CashierStringKey.TransactionsFieldTime to "Time",
        CashierStringKey.TransactionsFieldReceipt to "Receipt",
        CashierStringKey.TransactionsFieldSaleId to "Sale",
        CashierStringKey.TransactionsFieldTable to "Table",
        CashierStringKey.TransactionsFieldCashier to "Cashier",
        CashierStringKey.TransactionsFieldCorrectionActor to "Corrected by",
        CashierStringKey.TransactionsFieldAmount to "Amount",
        CashierStringKey.TransactionsFieldPaymentMethod to "Payment",
        CashierStringKey.TransactionsFieldStatus to "Status",
        CashierStringKey.TransactionsFieldSync to "Sync",
        CashierStringKey.TransactionsFieldPublicReceipt to "Public receipt",
        CashierStringKey.TransactionsFieldUpdated to "Updated",
        CashierStringKey.TransactionsUnavailable to "No authoritative value",
        CashierStringKey.TransactionsWalkIn to "Walk-in",
        CashierStringKey.TransactionsTimelineOpened to "Bill opened",
        CashierStringKey.TransactionsTimelineTransferred to "Bill transferred",
        CashierStringKey.TransactionsTimelineFinalized to "Payment finalized locally",
        CashierStringKey.TransactionsTimelineSynced to "Sale synced to backend",
        CashierStringKey.TransactionsTimelineFailed to "Backend sync failed",
        CashierStringKey.TransactionsTimelineBlocked to "Backend rejected sale",
        CashierStringKey.TransactionsPublicReceiptReady to "Ready",
        CashierStringKey.TransactionsPublicReceiptPending to "Not available yet",
    ),
)
