package com.airos.pos.app

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

internal enum class CashierLanguage {
    FI,
    EN,
}

internal enum class CashierStringKey {
    RailActive,
    RailTables,
    RailMenu,
    RailTransactions,
    RailReservations,
    RailCameras,
    RailScan,
    RailShift,
    RailStaff,
    RailSettings,
    RailSignOut,
    StaffMenuTitle,
    StaffMenuPrompt,
    StaffMenuSignOut,
    StaffMenuAuthTitle,
    StaffMenuAuthPrompt,
    StaffMenuAuthCancel,
    StaffMenuSellerToastPrefix,
    StaffMenuAlreadyActivePrefix,
    ReservationsTitle,
    ReservationsSelectTable,
    ReservationsNoTableSelected,
    TransactionsTitle,
    TransactionsSupporting,
    TransactionsCurrent,
    TransactionsPast,
    TransactionsSearchPlaceholder,
    TransactionsRangeAll,
    TransactionsRangeToday,
    TransactionsRangeLast7Days,
    TransactionsRangeLast30Days,
    TransactionsFilterAll,
    TransactionsStatusOpen,
    TransactionsStatusPaid,
    TransactionsStatusSynced,
    TransactionsStatusPending,
    TransactionsStatusFailed,
    TransactionsStatusBlocked,
    TransactionsPaymentAll,
    TransactionsPaymentCash,
    TransactionsPaymentCard,
    TransactionsPaymentVoucher,
    TransactionsPaymentMixed,
    TransactionsListEmptyCurrent,
    TransactionsListEmptyPast,
    TransactionsDetailEmpty,
    TransactionsCurrentSummary,
    TransactionsReceiptPreview,
    TransactionsTimeline,
    TransactionsTimelineEmpty,
    TransactionsActionReprint,
    TransactionsActionRefund,
    TransactionsActionCorrect,
    TransactionsNoLineItems,
    TransactionsSubtotal,
    TransactionsDiscount,
    TransactionsTax,
    TransactionsTotal,
    TransactionsFieldTime,
    TransactionsFieldReceipt,
    TransactionsFieldSaleId,
    TransactionsFieldTable,
    TransactionsFieldCashier,
    TransactionsFieldCorrectionActor,
    TransactionsFieldAmount,
    TransactionsFieldPaymentMethod,
    TransactionsFieldStatus,
    TransactionsFieldSync,
    TransactionsFieldPublicReceipt,
    TransactionsFieldUpdated,
    TransactionsUnavailable,
    TransactionsWalkIn,
    TransactionsTimelineOpened,
    TransactionsTimelineTransferred,
    TransactionsTimelineFinalized,
    TransactionsTimelineSynced,
    TransactionsTimelineFailed,
    TransactionsTimelineBlocked,
    TransactionsPublicReceiptReady,
    TransactionsPublicReceiptPending,

    // Sales dashboard
    SalesDashboardToday,
    SalesDashboardLastHour,
    SalesDashboardReceiptCount,
    SalesDashboardOpenBillsKpi,
    SalesDashboardHourlySales,
    SalesDashboardByCategory,
    SalesDashboardCategoryOther,
    SalesDashboardPaymentMethods,
    SalesDashboardRecentSales,
    SalesDashboardOpenBillsSection,
    SalesDashboardNoData,
    SalesDashboardNoHourlyData,
    SalesDashboardNoCategoryData,
    SalesDashboardNoOpenBills,
    SalesDashboardOpenBillDetail,
    SalesDashboardSelectSaleHint,
    SalesDashboardReprintDialogTitle,
    SalesDashboardReprintDialogBody,
    SalesDashboardRefundDialogTitle,
    SalesDashboardRefundDialogBody,
    SalesDashboardCorrectDialogTitle,
    SalesDashboardCorrectDialogBody,
    SalesDashboardDialogOk,
}

internal class CashierStrings(private val language: CashierLanguage) {
    operator fun get(key: CashierStringKey): String {
        return cashierTranslations[language]?.get(key)
            ?: cashierTranslations[CashierLanguage.EN]?.get(key)
            ?: key.name
    }
}

@Composable
internal fun rememberCashierStrings(): CashierStrings {
    val language = remember { CashierLanguage.FI }
    return remember(language) { CashierStrings(language) }
}

private val cashierTranslations: Map<CashierLanguage, Map<CashierStringKey, String>> = mapOf(
    CashierLanguage.FI to mapOf(
        CashierStringKey.RailActive to "Aktiivinen",
        CashierStringKey.RailTables to "PÖYDÄT",
        CashierStringKey.RailMenu to "TUOTTEET",
        CashierStringKey.RailTransactions to "MYYNTI",
        CashierStringKey.RailReservations to "VARAUS",
        CashierStringKey.RailCameras to "KAMERAT",
        CashierStringKey.RailScan to "LUE",
        CashierStringKey.RailShift to "VUORO",
        CashierStringKey.RailStaff to "HENKILÖSTÖ",
        CashierStringKey.RailSettings to "ASETUKSET",
        CashierStringKey.RailSignOut to "ULOS",
        CashierStringKey.StaffMenuTitle to "Valitse myyjä",
        CashierStringKey.StaffMenuPrompt to "Kuka jatkaa kassalla?",
        CashierStringKey.StaffMenuSignOut to "Kirjaudu ulos kassalta",
        CashierStringKey.StaffMenuAuthTitle to "Vahvista myyjä",
        CashierStringKey.StaffMenuAuthPrompt to "Syötä PIN jatkaaksesi kassalla",
        CashierStringKey.StaffMenuAuthCancel to "Peruuta",
        CashierStringKey.StaffMenuSellerToastPrefix to "Myyjä",
        CashierStringKey.StaffMenuAlreadyActivePrefix to "Aktiivinen jo",
        CashierStringKey.ReservationsTitle to "Varaukset",
        CashierStringKey.ReservationsSelectTable to "Valitse pöytä",
        CashierStringKey.ReservationsNoTableSelected to "Ei valittua pöytää",
        CashierStringKey.TransactionsTitle to "Myynti",
        CashierStringKey.TransactionsSupporting to "Päivän myynnit ja avoimet laskut.",
        CashierStringKey.TransactionsCurrent to "Nykyiset",
        CashierStringKey.TransactionsPast to "Menneet",
        CashierStringKey.TransactionsSearchPlaceholder to "Hae kuittia, pöytää, kassahenkilöä tai myyntiä",
        CashierStringKey.TransactionsRangeAll to "Kaikki",
        CashierStringKey.TransactionsRangeToday to "Tänään",
        CashierStringKey.TransactionsRangeLast7Days to "7 pv",
        CashierStringKey.TransactionsRangeLast30Days to "30 pv",
        CashierStringKey.TransactionsFilterAll to "Kaikki",
        CashierStringKey.TransactionsStatusOpen to "Avoin",
        CashierStringKey.TransactionsStatusPaid to "Maksettu",
        CashierStringKey.TransactionsStatusSynced to "Synkattu",
        CashierStringKey.TransactionsStatusPending to "Odottaa synkkausta",
        CashierStringKey.TransactionsStatusFailed to "Synkkaus epäonnistui",
        CashierStringKey.TransactionsStatusBlocked to "Estetty",
        CashierStringKey.TransactionsPaymentAll to "Kaikki tavat",
        CashierStringKey.TransactionsPaymentCash to "Käteinen",
        CashierStringKey.TransactionsPaymentCard to "Kortti",
        CashierStringKey.TransactionsPaymentVoucher to "Etuseteli",
        CashierStringKey.TransactionsPaymentMixed to "Yhdistetty",
        CashierStringKey.TransactionsListEmptyCurrent to "Ei avoimia myyntejä nykyisillä rajauksilla.",
        CashierStringKey.TransactionsListEmptyPast to "Ei menneitä myyntejä nykyisillä rajauksilla.",
        CashierStringKey.TransactionsDetailEmpty to "Valitse myynti oikean paneelin lisätietoihin.",
        CashierStringKey.TransactionsCurrentSummary to "Avoimen laskun yhteenveto",
        CashierStringKey.TransactionsReceiptPreview to "Kuitti",
        CashierStringKey.TransactionsTimeline to "Tapahtumaketju",
        CashierStringKey.TransactionsTimelineEmpty to "Ei authoritatiivista tapahtumaketjua tästä lähteestä.",
        CashierStringKey.TransactionsActionReprint to "Tulosta uudelleen",
        CashierStringKey.TransactionsActionRefund to "Hyvitä",
        CashierStringKey.TransactionsActionCorrect to "Korjaa myyntiä",
        CashierStringKey.TransactionsNoLineItems to "Ei rivejä.",
        CashierStringKey.TransactionsSubtotal to "Välisumma",
        CashierStringKey.TransactionsDiscount to "Alennus",
        CashierStringKey.TransactionsTax to "Vero",
        CashierStringKey.TransactionsTotal to "Yhteensä",
        CashierStringKey.TransactionsFieldTime to "Aika",
        CashierStringKey.TransactionsFieldReceipt to "Kuitti",
        CashierStringKey.TransactionsFieldSaleId to "Myynti",
        CashierStringKey.TransactionsFieldTable to "Pöytä",
        CashierStringKey.TransactionsFieldCashier to "Myynnin teki",
        CashierStringKey.TransactionsFieldCorrectionActor to "Korjasi",
        CashierStringKey.TransactionsFieldAmount to "Summa",
        CashierStringKey.TransactionsFieldPaymentMethod to "Maksutapa",
        CashierStringKey.TransactionsFieldStatus to "Tila",
        CashierStringKey.TransactionsFieldSync to "Synkkaus",
        CashierStringKey.TransactionsFieldPublicReceipt to "Sähköinen kuitti",
        CashierStringKey.TransactionsFieldUpdated to "Päivitetty",
        CashierStringKey.TransactionsUnavailable to "Ei tietoa",
        CashierStringKey.TransactionsWalkIn to "Walk-in",
        CashierStringKey.TransactionsTimelineOpened to "Lasku avattu",
        CashierStringKey.TransactionsTimelineTransferred to "Lasku siirretty",
        CashierStringKey.TransactionsTimelineFinalized to "Maksu viimeistelty paikallisesti",
        CashierStringKey.TransactionsTimelineSynced to "Myynti synkattu backendiin",
        CashierStringKey.TransactionsTimelineFailed to "Backend-synkkaus epäonnistui",
        CashierStringKey.TransactionsTimelineBlocked to "Backend hylkäsi myynnin",
        CashierStringKey.TransactionsPublicReceiptReady to "Valmis",
        CashierStringKey.TransactionsPublicReceiptPending to "Ei vielä saatavilla",

        CashierStringKey.SalesDashboardToday to "Tänään",
        CashierStringKey.SalesDashboardLastHour to "Viimeinen tunti",
        CashierStringKey.SalesDashboardReceiptCount to "Kuitteja",
        CashierStringKey.SalesDashboardOpenBillsKpi to "Avoimia laskuja",
        CashierStringKey.SalesDashboardHourlySales to "Myynti tunneittain",
        CashierStringKey.SalesDashboardByCategory to "Kategorioittain",
        CashierStringKey.SalesDashboardCategoryOther to "Muut",
        CashierStringKey.SalesDashboardPaymentMethods to "Maksutavat",
        CashierStringKey.SalesDashboardRecentSales to "Viimeisimmät myynnit",
        CashierStringKey.SalesDashboardOpenBillsSection to "Avoimet laskut",
        CashierStringKey.SalesDashboardNoData to "Ei myyntejä tänään",
        CashierStringKey.SalesDashboardNoHourlyData to "Ei tuntidataa tänään",
        CashierStringKey.SalesDashboardNoCategoryData to "Ei kategoriadataa",
        CashierStringKey.SalesDashboardNoOpenBills to "Ei avoimia laskuja",
        CashierStringKey.SalesDashboardOpenBillDetail to "Avoin lasku",
        CashierStringKey.SalesDashboardSelectSaleHint to "Valitse myynti nähdäksesi kuitin.",
        CashierStringKey.SalesDashboardReprintDialogTitle to "Tulosta uudelleen",
        CashierStringKey.SalesDashboardReprintDialogBody to "Uudelleentulostus kytketään kuittitulostuksen lopulliseen raporttipolkuun. Alkuperäinen kuittitotuus säilyy muuttumattomana.",
        CashierStringKey.SalesDashboardRefundDialogTitle to "Hyvitä",
        CashierStringKey.SalesDashboardRefundDialogBody to "Hyvitysketju säilyttää alkuperäisen kuitin ja luo erillisen hyvityskuitin. Rahapolku aktivoidaan seuraavassa paketissa.",
        CashierStringKey.SalesDashboardCorrectDialogTitle to "Korjaa myyntiä",
        CashierStringKey.SalesDashboardCorrectDialogBody to "Korjausketju tehdään erillisellä korjauskuitilla. Alkuperäistä myyntiä ei poisteta eikä ylikirjoiteta.",
        CashierStringKey.SalesDashboardDialogOk to "Selvä",
    ),
    CashierLanguage.EN to mapOf(
        CashierStringKey.RailActive to "Active",
        CashierStringKey.RailTables to "TABLES",
        CashierStringKey.RailMenu to "PRODUCTS",
        CashierStringKey.RailTransactions to "SALES",
        CashierStringKey.RailReservations to "BOOKINGS",
        CashierStringKey.RailCameras to "CAMERAS",
        CashierStringKey.RailScan to "SCAN",
        CashierStringKey.RailShift to "SHIFT",
        CashierStringKey.RailStaff to "STAFF",
        CashierStringKey.RailSettings to "SETTINGS",
        CashierStringKey.RailSignOut to "SIGN OUT",
        CashierStringKey.StaffMenuTitle to "Switch seller",
        CashierStringKey.StaffMenuPrompt to "Who is taking over?",
        CashierStringKey.StaffMenuSignOut to "Sign out",
        CashierStringKey.StaffMenuAuthTitle to "Confirm seller",
        CashierStringKey.StaffMenuAuthPrompt to "Enter PIN to continue at the register",
        CashierStringKey.StaffMenuAuthCancel to "Cancel",
        CashierStringKey.StaffMenuSellerToastPrefix to "Seller",
        CashierStringKey.StaffMenuAlreadyActivePrefix to "Already active",
        CashierStringKey.ReservationsTitle to "Reservations",
        CashierStringKey.ReservationsSelectTable to "Select table",
        CashierStringKey.ReservationsNoTableSelected to "No table selected",
        CashierStringKey.TransactionsTitle to "Sales",
        CashierStringKey.TransactionsSupporting to "Today's sales and open bills.",
        CashierStringKey.TransactionsCurrent to "Current",
        CashierStringKey.TransactionsPast to "Past",
        CashierStringKey.TransactionsSearchPlaceholder to "Search receipt, table, cashier, or sale",
        CashierStringKey.TransactionsRangeAll to "All",
        CashierStringKey.TransactionsRangeToday to "Today",
        CashierStringKey.TransactionsRangeLast7Days to "7 days",
        CashierStringKey.TransactionsRangeLast30Days to "30 days",
        CashierStringKey.TransactionsFilterAll to "All",
        CashierStringKey.TransactionsStatusOpen to "Open",
        CashierStringKey.TransactionsStatusPaid to "Paid",
        CashierStringKey.TransactionsStatusSynced to "Synced",
        CashierStringKey.TransactionsStatusPending to "Pending sync",
        CashierStringKey.TransactionsStatusFailed to "Sync failed",
        CashierStringKey.TransactionsStatusBlocked to "Blocked",
        CashierStringKey.TransactionsPaymentAll to "All methods",
        CashierStringKey.TransactionsPaymentCash to "Cash",
        CashierStringKey.TransactionsPaymentCard to "Card",
        CashierStringKey.TransactionsPaymentVoucher to "Voucher",
        CashierStringKey.TransactionsPaymentMixed to "Mixed",
        CashierStringKey.TransactionsListEmptyCurrent to "No open sales match the current filters.",
        CashierStringKey.TransactionsListEmptyPast to "No past sales match the current filters.",
        CashierStringKey.TransactionsDetailEmpty to "Select a sale to open the detail pane.",
        CashierStringKey.TransactionsCurrentSummary to "Open bill summary",
        CashierStringKey.TransactionsReceiptPreview to "Receipt",
        CashierStringKey.TransactionsTimeline to "Timeline",
        CashierStringKey.TransactionsTimelineEmpty to "No authoritative timeline is available from this source.",
        CashierStringKey.TransactionsActionReprint to "Print again",
        CashierStringKey.TransactionsActionRefund to "Refund",
        CashierStringKey.TransactionsActionCorrect to "Correct sale",
        CashierStringKey.TransactionsNoLineItems to "No line items.",
        CashierStringKey.TransactionsSubtotal to "Subtotal",
        CashierStringKey.TransactionsDiscount to "Discount",
        CashierStringKey.TransactionsTax to "Tax",
        CashierStringKey.TransactionsTotal to "Total",
        CashierStringKey.TransactionsFieldTime to "Time",
        CashierStringKey.TransactionsFieldReceipt to "Receipt",
        CashierStringKey.TransactionsFieldSaleId to "Sale",
        CashierStringKey.TransactionsFieldTable to "Table",
        CashierStringKey.TransactionsFieldCashier to "Cashier",
        CashierStringKey.TransactionsFieldCorrectionActor to "Corrected by",
        CashierStringKey.TransactionsFieldAmount to "Amount",
        CashierStringKey.TransactionsFieldPaymentMethod to "Payment",
        CashierStringKey.TransactionsFieldStatus to "Status",
        CashierStringKey.TransactionsFieldSync to "Sync",
        CashierStringKey.TransactionsFieldPublicReceipt to "Digital receipt",
        CashierStringKey.TransactionsFieldUpdated to "Updated",
        CashierStringKey.TransactionsUnavailable to "No data",
        CashierStringKey.TransactionsWalkIn to "Walk-in",
        CashierStringKey.TransactionsTimelineOpened to "Bill opened",
        CashierStringKey.TransactionsTimelineTransferred to "Bill transferred",
        CashierStringKey.TransactionsTimelineFinalized to "Payment finalized locally",
        CashierStringKey.TransactionsTimelineSynced to "Sale synced to backend",
        CashierStringKey.TransactionsTimelineFailed to "Backend sync failed",
        CashierStringKey.TransactionsTimelineBlocked to "Backend rejected sale",
        CashierStringKey.TransactionsPublicReceiptReady to "Ready",
        CashierStringKey.TransactionsPublicReceiptPending to "Not available yet",

        CashierStringKey.SalesDashboardToday to "Today",
        CashierStringKey.SalesDashboardLastHour to "Last hour",
        CashierStringKey.SalesDashboardReceiptCount to "Receipts",
        CashierStringKey.SalesDashboardOpenBillsKpi to "Open bills",
        CashierStringKey.SalesDashboardHourlySales to "Hourly sales",
        CashierStringKey.SalesDashboardByCategory to "By category",
        CashierStringKey.SalesDashboardCategoryOther to "Other",
        CashierStringKey.SalesDashboardPaymentMethods to "Payment methods",
        CashierStringKey.SalesDashboardRecentSales to "Recent sales",
        CashierStringKey.SalesDashboardOpenBillsSection to "Open bills",
        CashierStringKey.SalesDashboardNoData to "No sales today",
        CashierStringKey.SalesDashboardNoHourlyData to "No hourly data today",
        CashierStringKey.SalesDashboardNoCategoryData to "No category data",
        CashierStringKey.SalesDashboardNoOpenBills to "No open bills",
        CashierStringKey.SalesDashboardOpenBillDetail to "Open bill",
        CashierStringKey.SalesDashboardSelectSaleHint to "Select a sale to view the receipt.",
        CashierStringKey.SalesDashboardReprintDialogTitle to "Print again",
        CashierStringKey.SalesDashboardReprintDialogBody to "Reprinting will be connected to the final receipt reporting path. The original receipt truth stays unchanged.",
        CashierStringKey.SalesDashboardRefundDialogTitle to "Refund",
        CashierStringKey.SalesDashboardRefundDialogBody to "The refund chain preserves the original receipt and creates a separate refund receipt. Payment path activated in the next package.",
        CashierStringKey.SalesDashboardCorrectDialogTitle to "Correct sale",
        CashierStringKey.SalesDashboardCorrectDialogBody to "The correction chain uses a separate correction receipt. The original sale is not deleted or overwritten.",
        CashierStringKey.SalesDashboardDialogOk to "OK",
    ),
)
