package com.airos.pos.app

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

internal enum class CashierLanguage {
    FI,
    EN,
}

internal enum class CashierStringKey {
    RailActive,
    RailTables,
    RailMenu,
    RailTransactions,
    RailReservations,
    RailScan,
    RailShift,
    RailSettings,
    RailSignOut,
    ReservationsTitle,
    ReservationsSelectTable,
    ReservationsNoTableSelected,
    TransactionsTitle,
    TransactionsSupporting,
    TransactionsCurrent,
    TransactionsPast,
    TransactionsSearchPlaceholder,
    TransactionsRangeAll,
    TransactionsRangeToday,
    TransactionsRangeLast7Days,
    TransactionsRangeLast30Days,
    TransactionsFilterAll,
    TransactionsStatusOpen,
    TransactionsStatusPaid,
    TransactionsStatusSynced,
    TransactionsStatusPending,
    TransactionsStatusFailed,
    TransactionsStatusBlocked,
    TransactionsPaymentAll,
    TransactionsPaymentCash,
    TransactionsPaymentCard,
    TransactionsPaymentVoucher,
    TransactionsPaymentMixed,
    TransactionsListEmptyCurrent,
    TransactionsListEmptyPast,
    TransactionsDetailEmpty,
    TransactionsCurrentSummary,
    TransactionsReceiptPreview,
    TransactionsTimeline,
    TransactionsTimelineEmpty,
    TransactionsActionReprint,
    TransactionsActionRefund,
    TransactionsActionCorrect,
    TransactionsNoLineItems,
    TransactionsSubtotal,
    TransactionsDiscount,
    TransactionsTax,
    TransactionsTotal,
    TransactionsFieldTime,
    TransactionsFieldReceipt,
    TransactionsFieldSaleId,
    TransactionsFieldTable,
    TransactionsFieldCashier,
    TransactionsFieldCorrectionActor,
    TransactionsFieldAmount,
    TransactionsFieldPaymentMethod,
    TransactionsFieldStatus,
    TransactionsFieldSync,
    TransactionsFieldPublicReceipt,
    TransactionsFieldUpdated,
    TransactionsUnavailable,
    TransactionsWalkIn,
    TransactionsTimelineOpened,
    TransactionsTimelineTransferred,
    TransactionsTimelineFinalized,
    TransactionsTimelineSynced,
    TransactionsTimelineFailed,
    TransactionsTimelineBlocked,
    TransactionsPublicReceiptReady,
    TransactionsPublicReceiptPending,
}

internal class CashierStrings(private val language: CashierLanguage) {
    operator fun get(key: CashierStringKey): String {
        return cashierTranslations[language]?.get(key)
            ?: cashierTranslations[CashierLanguage.EN]?.get(key)
            ?: key.name
    }
}

@Composable
internal fun rememberCashierStrings(): CashierStrings {
    val language = remember { CashierLanguage.FI }
    return remember(language) { CashierStrings(language) }
}

private val cashierTranslations: Map<CashierLanguage, Map<CashierStringKey, String>> = mapOf(
    CashierLanguage.FI to mapOf(
        CashierStringKey.RailActive to "Aktiivinen",
        CashierStringKey.RailTables to "Pöydät",
        CashierStringKey.RailMenu to "Menu",
        CashierStringKey.RailTransactions to "Myynti",
        CashierStringKey.RailReservations to "Varaus",
        CashierStringKey.RailScan to "Lue",
        CashierStringKey.RailShift to "Vuoro",
        CashierStringKey.RailSettings to "Asetukset",
        CashierStringKey.RailSignOut to "Ulos",
        CashierStringKey.ReservationsTitle to "Varaukset",
        CashierStringKey.ReservationsSelectTable to "Valitse pöytä",
        CashierStringKey.ReservationsNoTableSelected to "Ei valittua pöytää",
        CashierStringKey.TransactionsTitle to "Myynti",
        CashierStringKey.TransactionsSupporting to "Nykyiset myynnit tulevat avoimista laskuista. Menneet myynnit tulevat paikallisesta myyntilokista.",
        CashierStringKey.TransactionsCurrent to "Nykyiset",
        CashierStringKey.TransactionsPast to "Menneet",
        CashierStringKey.TransactionsSearchPlaceholder to "Hae kuittia, pöytää, kassahenkilöä tai myyntiä",
        CashierStringKey.TransactionsRangeAll to "Kaikki",
        CashierStringKey.TransactionsRangeToday to "Tänään",
        CashierStringKey.TransactionsRangeLast7Days to "7 pv",
        CashierStringKey.TransactionsRangeLast30Days to "30 pv",
        CashierStringKey.TransactionsFilterAll to "Kaikki",
        CashierStringKey.TransactionsStatusOpen to "Avoin",
        CashierStringKey.TransactionsStatusPaid to "Maksettu",
        CashierStringKey.TransactionsStatusSynced to "Synkattu",
        CashierStringKey.TransactionsStatusPending to "Odottaa synkkausta",
        CashierStringKey.TransactionsStatusFailed to "Synkkaus epäonnistui",
        CashierStringKey.TransactionsStatusBlocked to "Estetty",
        CashierStringKey.TransactionsPaymentAll to "Kaikki tavat",
        CashierStringKey.TransactionsPaymentCash to "Käteinen",
        CashierStringKey.TransactionsPaymentCard to "Kortti",
        CashierStringKey.TransactionsPaymentVoucher to "Etuseteli",
        CashierStringKey.TransactionsPaymentMixed to "Yhdistetty",
        CashierStringKey.TransactionsListEmptyCurrent to "Ei avoimia myyntejä nykyisillä rajauksilla.",
        CashierStringKey.TransactionsListEmptyPast to "Ei menneitä myyntejä nykyisillä rajauksilla.",
        CashierStringKey.TransactionsDetailEmpty to "Valitse myynti oikean paneelin lisätietoihin.",
        CashierStringKey.TransactionsCurrentSummary to "Avoimen laskun yhteenveto",
        CashierStringKey.TransactionsReceiptPreview to "Kuittinäkymä",
        CashierStringKey.TransactionsTimeline to "Tapahtumaketju",
        CashierStringKey.TransactionsTimelineEmpty to "Ei authoritatiivista tapahtumaketjua tästä lähteestä.",
        CashierStringKey.TransactionsActionReprint to "Tulosta uudelleen",
        CashierStringKey.TransactionsActionRefund to "Hyvitä",
        CashierStringKey.TransactionsActionCorrect to "Korjaa myyntiä",
        CashierStringKey.TransactionsNoLineItems to "Ei rivejä.",
        CashierStringKey.TransactionsSubtotal to "Välisumma",
        CashierStringKey.TransactionsDiscount to "Alennus",
        CashierStringKey.TransactionsTax to "Vero",
        CashierStringKey.TransactionsTotal to "Yhteensä",
        CashierStringKey.TransactionsFieldTime to "Aika",
        CashierStringKey.TransactionsFieldReceipt to "Kuitti",
        CashierStringKey.TransactionsFieldSaleId to "Myynti",
        CashierStringKey.TransactionsFieldTable to "Pöytä",
        CashierStringKey.TransactionsFieldCashier to "Myynnin teki",
        CashierStringKey.TransactionsFieldCorrectionActor to "Korjasi",
        CashierStringKey.TransactionsFieldAmount to "Summa",
        CashierStringKey.TransactionsFieldPaymentMethod to "Maksutapa",
        CashierStringKey.TransactionsFieldStatus to "Tila",
        CashierStringKey.TransactionsFieldSync to "Synkkaus",
        CashierStringKey.TransactionsFieldPublicReceipt to "Julkinen kuitti",
        CashierStringKey.TransactionsFieldUpdated to "Päivitetty",
        CashierStringKey.TransactionsUnavailable to "Ei authoritatiivista tietoa",
        CashierStringKey.TransactionsWalkIn to "Walk-in",
        CashierStringKey.TransactionsTimelineOpened to "Lasku avattu",
        CashierStringKey.TransactionsTimelineTransferred to "Lasku siirretty",
        CashierStringKey.TransactionsTimelineFinalized to "Maksu viimeistelty paikallisesti",
        CashierStringKey.TransactionsTimelineSynced to "Myynti synkattu backendiin",
        CashierStringKey.TransactionsTimelineFailed to "Backend-synkkaus epäonnistui",
        CashierStringKey.TransactionsTimelineBlocked to "Backend hylkäsi myynnin",
        CashierStringKey.TransactionsPublicReceiptReady to "Valmis",
        CashierStringKey.TransactionsPublicReceiptPending to "Ei vielä saatavilla",
    ),
    CashierLanguage.EN to mapOf(
        CashierStringKey.RailActive to "Active",
        CashierStringKey.RailTables to "Tables",
        CashierStringKey.RailMenu to "Menu",
        CashierStringKey.RailTransactions to "Sales",
        CashierStringKey.RailReservations to "Bookings",
        CashierStringKey.RailScan to "Scan",
        CashierStringKey.RailShift to "Shift",
        CashierStringKey.RailSettings to "Settings",
        CashierStringKey.RailSignOut to "Sign out",
        CashierStringKey.ReservationsTitle to "Reservations",
        CashierStringKey.ReservationsSelectTable to "Select table",
        CashierStringKey.ReservationsNoTableSelected to "No table selected",
        CashierStringKey.TransactionsTitle to "Sales",
        CashierStringKey.TransactionsSupporting to "Current sales come from open bill truth. Past sales come from the durable local sales ledger outbox.",
        CashierStringKey.TransactionsCurrent to "Current",
        CashierStringKey.TransactionsPast to "Past",
        CashierStringKey.TransactionsSearchPlaceholder to "Search receipt, table, cashier, or sale",
        CashierStringKey.TransactionsRangeAll to "All",
        CashierStringKey.TransactionsRangeToday to "Today",
        CashierStringKey.TransactionsRangeLast7Days to "7 days",
        CashierStringKey.TransactionsRangeLast30Days to "30 days",
        CashierStringKey.TransactionsFilterAll to "All",
        CashierStringKey.TransactionsStatusOpen to "Open",
        CashierStringKey.TransactionsStatusPaid to "Paid",
        CashierStringKey.TransactionsStatusSynced to "Synced",
        CashierStringKey.TransactionsStatusPending to "Pending sync",
        CashierStringKey.TransactionsStatusFailed to "Sync failed",
        CashierStringKey.TransactionsStatusBlocked to "Blocked",
        CashierStringKey.TransactionsPaymentAll to "All methods",
        CashierStringKey.TransactionsPaymentCash to "Cash",
        CashierStringKey.TransactionsPaymentCard to "Card",
        CashierStringKey.TransactionsPaymentVoucher to "Voucher",
        CashierStringKey.TransactionsPaymentMixed to "Mixed",
        CashierStringKey.TransactionsListEmptyCurrent to "No open sales match the current filters.",
        CashierStringKey.TransactionsListEmptyPast to "No past sales match the current filters.",
        CashierStringKey.TransactionsDetailEmpty to "Select a sale to open the detail pane.",
        CashierStringKey.TransactionsCurrentSummary to "Open bill summary",
        CashierStringKey.TransactionsReceiptPreview to "Receipt preview",
        CashierStringKey.TransactionsTimeline to "Timeline",
        CashierStringKey.TransactionsTimelineEmpty to "No authoritative timeline is available from this source.",
        CashierStringKey.TransactionsActionReprint to "Print again",
        CashierStringKey.TransactionsActionRefund to "Refund",
        CashierStringKey.TransactionsActionCorrect to "Correct sale",
        CashierStringKey.TransactionsNoLineItems to "No line items.",
        CashierStringKey.TransactionsSubtotal to "Subtotal",
        CashierStringKey.TransactionsDiscount to "Discount",
        CashierStringKey.TransactionsTax to "Tax",
        CashierStringKey.TransactionsTotal to "Total",
        CashierStringKey.TransactionsFieldTime to "Time",
        CashierStringKey.TransactionsFieldReceipt to "Receipt",
        CashierStringKey.TransactionsFieldSaleId to "Sale",
        CashierStringKey.TransactionsFieldTable to "Table",
        CashierStringKey.TransactionsFieldCashier to "Cashier",
        CashierStringKey.TransactionsFieldCorrectionActor to "Corrected by",
        CashierStringKey.TransactionsFieldAmount to "Amount",
        CashierStringKey.TransactionsFieldPaymentMethod to "Payment",
        CashierStringKey.TransactionsFieldStatus to "Status",
        CashierStringKey.TransactionsFieldSync to "Sync",
        CashierStringKey.TransactionsFieldPublicReceipt to "Public receipt",
        CashierStringKey.TransactionsFieldUpdated to "Updated",
        CashierStringKey.TransactionsUnavailable to "No authoritative value",
        CashierStringKey.TransactionsWalkIn to "Walk-in",
        CashierStringKey.TransactionsTimelineOpened to "Bill opened",
        CashierStringKey.TransactionsTimelineTransferred to "Bill transferred",
        CashierStringKey.TransactionsTimelineFinalized to "Payment finalized locally",
        CashierStringKey.TransactionsTimelineSynced to "Sale synced to backend",
        CashierStringKey.TransactionsTimelineFailed to "Backend sync failed",
        CashierStringKey.TransactionsTimelineBlocked to "Backend rejected sale",
        CashierStringKey.TransactionsPublicReceiptReady to "Ready",
        CashierStringKey.TransactionsPublicReceiptPending to "Not available yet",
    ),
)
